### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'divide')`

### ISSUE THREAD

**Issue by UshiOfficial** [Kromatika-Finance/interface#2]
## URL
  
https://app.kromatika.finance/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0x4F96Fe3b7A6Cf9725f59d353F723c1bDb64CA6Aa"
  },
  "PRICE": {
    "currencyId": null
  },
  "independentField": "PRICE",
  "fixedField": "INPUT",
  "typedValue": "4000.91",
  "inputValue": "1",
  "recipient": null
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading 'divide')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'divide')
    at new t (https://app.kromatika.finance/static/js/35.b687bb54.chunk.js:2:66324)
    at https://app.kromatika.finance/static/js/main.fc6bc7d2.chunk.js:1:236294
    at Object.Aa [as useMemo] (https://app.kromatika.finance/static/js/35.b687bb54.chunk.js:2:1118147)
    at t.useMemo (https://app.kromatika.finance/static/js/35.b687bb54.chunk.js:2:1053167)
    at Fd (https://app.kromatika.finance/static/js/main.fc6bc7d2.chunk.js:1:236270)
    at IC (https://app.kromatika.finance/static/js/main.fc6bc7d2.chunk.js:1:602742)
    at ua (https://app.kromatika.finance/static/js/35.b687bb54.chunk.js:2:1113414)
    at Wa (https://app.kromatika.finance/static/js/35.b687bb54.chunk.js:2:1122981)
    at Ku (https://app.kromatika.finance/static/js/35.b687bb54.chunk.js:2:1166705)
    at Ps (https://app.kromatika.finance/static/js/35.b687bb54.chunk.js:2:1152955)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.45",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.45"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by Aristokrates** [comment]
Fixed in the latest version.
