### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by SceleTOhm** [Kromatika-Finance/interface#4]
## URL
  
https://app.kromatika.finance/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984"
  },
  "OUTPUT": {
    "currencyId": "0x4F96Fe3b7A6Cf9725f59d353F723c1bDb64CA6Aa"
  },
  "PRICE": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "fixedField": "INPUT",
  "typedValue": "0.05",
  "inputValue": "0.05",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at https://app.kromatika.finance/static/js/35.b687bb54.chunk.js:2:84774
    at t.quote (https://app.kromatika.finance/static/js/35.b687bb54.chunk.js:2:67055)
    at https://app.kromatika.finance/static/js/main.fc6bc7d2.chunk.js:1:236611
    at Object.Aa [as useMemo] (https://app.kromatika.finance/static/js/35.b687bb54.chunk.js:2:1118147)
    at https://app.kromatika.finance/static/js/35.b687bb54.chunk.js:2:1053167
    at Fd (https://app.kromatika.finance/static/js/main.fc6bc7d2.chunk.js:1:236513)
    at IC (https://app.kromatika.finance/static/js/main.fc6bc7d2.chunk.js:1:602742)
    at ua (https://app.kromatika.finance/static/js/35.b687bb54.chunk.js:2:1113414)
    at Wa (https://app.kromatika.finance/static/js/35.b687bb54.chunk.js:2:1122981)
    at Ku (https://app.kromatika.finance/static/js/35.b687bb54.chunk.js:2:1166705)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.45",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.45"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by Aristokrates** [comment]
Fixed in the latest version.
