### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'divide')`

### ISSUE THREAD

**Issue by slicken** [Kromatika-Finance/interface#5]
## URL
  
https://app.kromatika.finance/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000"
  },
  "OUTPUT": {
    "currencyId": "0x7F5c764cBc14f9669B88837ca1490cCa17c31607"
  },
  "PRICE": {
    "currencyId": null
  },
  "independentField": "PRICE",
  "fixedField": "INPUT",
  "typedValue": "",
  "inputValue": "0.00965681207950547",
  "recipient": null
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading 'divide')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'divide')
    at new t (https://app.kromatika.finance/static/js/35.0f1fa930.chunk.js:2:66324)
    at https://app.kromatika.finance/static/js/main.49aae30f.chunk.js:1:236225
    at Object.Aa [as useMemo] (https://app.kromatika.finance/static/js/35.0f1fa930.chunk.js:2:1131297)
    at https://app.kromatika.finance/static/js/35.0f1fa930.chunk.js:2:1066317
    at qd (https://app.kromatika.finance/static/js/main.49aae30f.chunk.js:1:236201)
    at kC (https://app.kromatika.finance/static/js/main.49aae30f.chunk.js:1:602260)
    at ua (https://app.kromatika.finance/static/js/35.0f1fa930.chunk.js:2:1126564)
    at Wa (https://app.kromatika.finance/static/js/35.0f1fa930.chunk.js:2:1136131)
    at $u (https://app.kromatika.finance/static/js/35.0f1fa930.chunk.js:2:1179855)
    at Ps (https://app.kromatika.finance/static/js/35.0f1fa930.chunk.js:2:1166105)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.110",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.110"
  },
  "os": {
    "name": "Linux",
    "version": "x86_64"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by Aristokrates** [comment]
Fixed in the latest version.
