### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'divide')`

### ISSUE THREAD

**Issue by codecD7** [Kromatika-Finance/interface#6]
## URL
  
https://app.kromatika.finance/?utm_source=DappRadar&utm_medium=deeplink&utm_campaign=visit-website#/swap

## `swap` state
    
```json
{
  "independentField": "PRICE",
  "fixedField": "INPUT",
  "typedValue": "0",
  "inputValue": "1026.718263529033056266",
  "INPUT": {
    "currencyId": "0xc13F4F0F865bAc08F62654B57E38669EbC4747a3"
  },
  "OUTPUT": {
    "currencyId": "ETH"
  },
  "PRICE": {
    "currencyId": ""
  },
  "recipient": null
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading 'divide')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'divide')
    at new t (https://app.kromatika.finance/static/js/35.0f1fa930.chunk.js:2:66324)
    at https://app.kromatika.finance/static/js/main.49aae30f.chunk.js:1:236225
    at Object.Aa [as useMemo] (https://app.kromatika.finance/static/js/35.0f1fa930.chunk.js:2:1131297)
    at t.useMemo (https://app.kromatika.finance/static/js/35.0f1fa930.chunk.js:2:1066317)
    at qd (https://app.kromatika.finance/static/js/main.49aae30f.chunk.js:1:236201)
    at kC (https://app.kromatika.finance/static/js/main.49aae30f.chunk.js:1:602260)
    at ua (https://app.kromatika.finance/static/js/35.0f1fa930.chunk.js:2:1126564)
    at Wa (https://app.kromatika.finance/static/js/35.0f1fa930.chunk.js:2:1136131)
    at $u (https://app.kromatika.finance/static/js/35.0f1fa930.chunk.js:2:1179855)
    at Ps (https://app.kromatika.finance/static/js/35.0f1fa930.chunk.js:2:1166105)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.110",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.110"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by Aristokrates** [comment]
Fixed in the latest version.
